<?php 
$links = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
$links = explode('?', $links);

$paramas = strtolower($_GET['area'] ? $_GET['area'] : '');

if ($paramas == 'cn')
	$steamclod = 'https://cloud.keysdeal.com/?'.$links[1];
else if($paramas == 'ru')
	$steamclod = 'https://cloud02.gamesdeal.com/?'.$links[1];
else
	exit('no server!!!');
?>

<iframe src="<?php echo $steamclod ?>" width="100%" height="600" style="margin: 0 auto;display: block;border: none;"></iframe>
